apiVersion: batch/v1
kind: Job

metadata:
  name: mysql-init
  namespace: medicare

spec:
  template:
    spec:
      containers:
      - name: mysql-init
        image: mysql:8

        command:
        - /bin/sh
        - -c
        - |
          mysql -h mysql-service -u root -proot123 medicare < /schema/schema.sql

        volumeMounts:
        - name: schema
          mountPath: /schema

      restartPolicy: Never

      volumes:
      - name: schema
        configMap:
          name: medicare-schema
